# Site settings
title: 戴远的IT博客
email: iamdaiyuan@gamil.com	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iamdaiyuan.github.io" # the base hostname & protocol for your site
twitter_username: iamdaiyuan
github_username:  iamdaiyuan