# Site settings
title: 胜利哥的...
email: iamdaiyuan@gamil.com	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iamdaiyuan.github.io" # the base hostname & protocol for your site
twitter_username: iamdaiyuan
github_username:  iamdaiyuan

# Build settings
markdown: kramdown
